@startuml
hide circle
skinparam classAttributeIconSize 0

class BillDetailController {
    - _billDetailRepository: IBillDetailRepository 
    + UpdateBillDetail(id: Guid, request: UpdateBillDetailRequestDTO): BillDetailResponseDTO
}

interface IBillDetailRepository {
    +UpdateBillDetail(id: Guid, request: UpdateBillDetailRequestDTO): Task<BillDetailResponseDTO>
}

class BillDetailRepository {
    - _billDetailDAO : BillDetailDAO
    +UpdateBillDetail(id: Guid, request: UpdateBillDetailRequestDTO): Task<BillDetailResponseDTO>
}

class BillDetailDAO {
    - _client: Supabase.Client
    +UpdateBillDetail(id: Guid, request: UpdateBillDetailRequestDTO): Task<BillDetailResponseDTO>
}

class BillDetail {
    +Id: Guid
    +MenuItemId: Guid
    +BillId: Guid
    +Quantity: int
    +Price: decimal
    +CreatedAt: DateTime
    +UpdatedAt: DateTime
}

class BillDetailResponseDTO {
    +Id: Guid
    +MenuItemId: Guid
    +BillId: Guid
    +Quantity: int
    +Price: decimal
    +CreatedAt: DateTime
    +UpdatedAt: DateTime
}

class UpdateBillDetailRequestDTO {
    +Quantity: int
    +Price: decimal
}

class ErrorHandler {
    +IsJson(input: string): bool
    +ProcessErrorMessage(exceptionMessage: string): string
}

class SupabaseClient {
    +Query(): object
}

BillDetailController -- IBillDetailRepository
IBillDetailRepository <|.. BillDetailRepository
BillDetailRepository -- BillDetailDAO
BillDetailDAO -- BillDetail
BillDetailResponseDTO -- BillDetailDAO
BillDetailDAO -- ErrorHandler
BillDetailDAO -- SupabaseClient
UpdateBillDetailRequestDTO -- BillDetailDAO

@enduml
