services:
  api-gateway:
    build:
      context: ./solution/APIGatewaySolution
      dockerfile: ApiGateway/Dockerfile
    ports:
      - '8000:8080'
    depends_on:
      - auth-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  auth-service:
    build:
      context: ./solution/AuthenticationSolution
      dockerfile: AuthService/Dockerfile
    volumes:
      - ./data-protection-keys:/home/app/.aspnet/DataProtection-Keys
    ports:
      - '5000:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SUPABASE_URL: https://cnbwnwbtafbarsgmcabf.supabase.co
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuYndud2J0YWZiYXJzZ21jYWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0MDM3NjEsImV4cCI6MjA0Njk3OTc2MX0.mNGsOKRoaTQdB7fG8OJiddqslin08Yvx3uR13hDFNAA
      DB_CONNECTION_STRING: 'Host=db;Database=postgres;Username=postgres;Password=ukjZocOd5LtG2WqN;SSL Mode=Disable'
