@startuml
hide circle
skinparam classAttributeIconSize 0

class TableTypeController {
    - _tableTypeRepository: ITableTypeRepository
    + CreateTableType(createTableType: AddEditTypeRequestDTO): Task<IActionResult>
}

interface ITableTypeRepository {
    + CreateTableType(createTableType: AddEditTypeRequestDTO): Task<GetTableTypeResponseDTO>
}

class TableTypeRepository {
    - _tableTypeDao: TableTypeDAO
    + CreateTableType(createTableType: AddEditTypeRequestDTO): Task<GetTableTypeResponseDTO>
}

class TableTypeDAO {
    - _client: Supabase.Client
    + CreateTableType(createTableType: AddEditTypeRequestDTO): Task<GetTableTypeResponseDTO>
}

class TableType {
    + Id: Guid
    + Name: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

class AddEditTypeRequestDTO {
    + Name: string
    + Description: string?
}

class GetTableTypeResponseDTO {
    + Id: Guid
    + Name: string
    + Description: string?
    + CreatedAt: DateTime
    + UpdatedAt: DateTime?
}

class ErrorHandler {
    + IsJson(input: string): bool
    + ProcessErrorMessage(exceptionMessage: string): string
}

TableTypeController -- ITableTypeRepository
ITableTypeRepository <|-- TableTypeRepository
TableTypeRepository -- TableTypeDAO

TableTypeDAO -- TableType
TableTypeDAO -- ErrorHandler
TableTypeDAO -- GetTableTypeResponseDTO
TableTypeDAO -- AddEditTypeRequestDTO
@enduml
