@startuml
hide circle
skinparam classAttributeIconSize 0

class APIGateway {
}

class TableTypeController {
    - _tableTypeRepository: ITableTypeRepository
    + GetAllTableTypes(): Task<IActionResult>
}

interface ITableTypeRepository<<interface>>  {
    + GetAllTableTypes(): Task<List<GetTableTypeResponseDTO>>
}

class TableTypeRepository {
    - _tableTypeDao: TableTypeDAO
    + GetAllTableTypes(): Task<List<GetTableTypeResponseDTO>>
}

class TableTypeDAO {
    - _client: Client
    + GetAllTableTypes(): Task<List<GetTableTypeResponseDTO>>
}

class TableType {
    + Id: Guid
    + Name: string
    + Description: string
    + PriceByHour: decimal
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

APIGateway -- TableTypeController
TableTypeController -- ITableTypeRepository
ITableTypeRepository <|-- TableTypeRepository
TableTypeRepository -- TableTypeDAO
TableTypeDAO -- TableType

@enduml
