@startuml
hide circle
skinparam classAttributeIconSize 0

class TableTypeController {
    - _tableTypeRepository: ITableTypeRepository
    + UpdateTableType(Guid id, AddEditTypeRequestDTO updateTableType): Task<IActionResult>
}

interface ITableTypeRepository<<interface>>  {
    + UpdateTableType(Guid id, AddEditTypeRequestDTO updateTableType): Task<GetTableTypeResponseDTO>
}

class TableTypeRepository {
    - _tableTypeDao: TableTypeDAO
    + UpdateTableType(Guid id, AddEditTypeRequestDTO updateTableType): Task<GetTableTypeResponseDTO>
}

class TableTypeDAO {
    - _client: Client
    + UpdateTableType(Guid id, AddEditTypeRequestDTO updateTableType): Task<GetTableTypeResponseDTO>
}

class TableType {
    + Id: Guid
    + Name: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}


TableTypeController -- ITableTypeRepository
ITableTypeRepository <|-- TableTypeRepository
TableTypeRepository -- TableTypeDAO

TableTypeDAO -- TableType
@enduml