label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: chat application
apiGateway: apiGateway
AuthController: authController
AuthRepository: authRepository
AuthDAO: authDAO

DB: "DB" {
  shape: cylinder
}

User -> application.post: "1. Navigate to login page"
User -> application.post: "2. Enter credentials and submit login form"
application -> apiGateway.post: "3. Forward login request"
apiGateway -> AuthController.post: "4. Authenticate user"
AuthController -> AuthRepository.post: "5. Forward to repository"
AuthRepository -> AuthDAO.post: "6. Forward to DAO"
AuthDAO -> Supabase.Auth: "7. Validate user credentials"

# Check credentials in the database
Supabase.Auth -> DB.query: "8. Check user in database"
Supabase -> Supabase.Auth.response: "9. Return user record"

alt: "alt" {
  class: frame
  Incorrect credentials: "[Incorrect credentials]" {
  # Conditional branch for incorrect credentials
  Supabase.Auth -> AuthDAO.post: "10a. Invalid credentials" {class: return arrow}
  AuthDAO -> AuthRepository.post: "11a. Forward error" {class: return arrow}
  AuthRepository -> AuthController.post: "12a. Return error" {class: return arrow}

  AuthController -> apiGateway.post: "13a. Send error to frontend" {class: return arrow}
  apiGateway -> application.post: "14a. Return error" {class: return arrow}
  application -> User: "15a. Display error message" {class: return arrow}
  }
  Correct credentials: "[Correct credentials]" {
    # Successful login branch
  Supabase.Auth -> Supabase.Auth.post: "10b. Generate token" 
  Supabase.Auth -> AuthDAO.post: "11b. Return access token" {class: return arrow}
  AuthDAO -> AuthRepository.post: "12b. Forward token" {class: return arrow}
  AuthRepository -> AuthController.post: "13b. Return token" {class: return arrow}
  AuthController -> apiGateway.post: "14b. Send token to frontend" {class: return arrow}
  apiGateway -> application.post: "15b. Return token" {class: return arrow}
  application -> User: "16b. Store token and login success" {class: return arrow}
  }
}



