label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return_arrow: {
    style: {
      stroke-dash: 3
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label_right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: "Application"
apiGateway: "API Gateway"
TableController: "TableController"
TableRepository: "TableRepository"
TableDAO: "TableDAO"
DB: "DB" {
  shape: cylinder
}
User -> application.bar: "1. Select a table"
application -> apiGateway.bar: "2. Forward request"
apiGateway -> TableController.bar: "3. Forward to TableController"
TableController -> TableRepository.bar: "4. Call GetTableById()"
TableRepository -> TableDAO.bar: "5. Fetch tables from DB"
TableDAO -> DB.bar: "6. Query table details"
DB.bar -> TableDAO.bar: "7. Return table details" {class:return_arrow}
TableDAO.bar -> TableRepository.bar: "8. Return response"{class:return_arrow}
TableRepository.bar -> TableController.bar: "9. Return response"{class:return_arrow}

alt {
  class: frame
  "No table found": {
    TableController.bar -> apiGateway.bar: "9.1. Send 404 error notification"{class:return_arrow}
    apiGateway.bar -> application.bar: "9.1.1. Forward response"{class:return_arrow}
    application.bar -> User: "9.1.1.1. Display 404 error notification"{class:return_arrow}
  }
  "Tables found": {
    TableController.bar -> apiGateway.bar: "9.2. Send response"{class:return_arrow}
    apiGateway.bar -> application.bar: "9.2.1. Forward response"{class:return_arrow}
    application.bar -> User: "9.2.1.1. Display table information"{class:return_arrow}
  }
}
