label: "Sequence Diagram for UpdateUser"

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }
  return_arrow: {
    style: {
      stroke-dash: 3
    }
  }
  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }
  label_right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: "Web application"
apiGateway: "ApiGateway"
UserController: "UserController"
UserRepository: "UserRepository"
UserDAO: "UserDAO"
Supabase: "Supabase"
DB: "DB" {
  shape: cylinder
}

User -> application.get: "1. Get all product request"
application.get -> apiGateway.get: "2. Request get alls product"
apiGateway.get -> UserController.get: "3. Forward request"
UserController -> UserRepository.get: "4. Forward request to repository"
UserRepository -> UserDAO.get: "5. Forward request to DAO"

UserDAO.get -> Supabase.get: "6. Validate token"
Supabase.get -> DB.get: "7. Get all product"
DB.get -> Supabase.get: "8. Return result"
Supabase.get -> UserDAO.get: "9. Return result"
UserDAO.get -> UserRepository.get: "10. Return result" {class: return arrow}
UserRepository.get-> UserController.get: "11. Forward result" {class: return arrow}

alt: "alt" {
  class: frame
  Product found: "[Get List Product]" {
    UserController.get -> apiGateway.get: "11.1. Send product list" {class: return arrow}
    apiGateway.get -> application.get: "11.1.1. Send product list" {class: return arrow}
    application.get -> User: "11.1.2. Display product list" {class: return arrow}
  }
  Get Product failed: "[Get Product failed]" {
    UserController.get -> apiGateway.get: "11.2. Send error to frontend" {class: return arrow}
    apiGateway.get -> application.get: "11.2.1. Return error" {class: return arrow}
    application.get -> User: "11.2.2. Display error message" {class: return arrow}
  }
}