label: "Sequence Diagram for UpdateUser"

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }
  return_arrow: {
    style: {
      stroke-dash: 3
    }
  }
  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }
  label_right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: "Web application"
apiGateway: "ApiGateway"
ProductController: "ProductController"
ProductRepositories: "ProductRepositories"
ProductDAO: "ProductDAO"
Supabase: "Supabase"
DB: "DB" {
  shape: cylinder
}

loop  { 
  class: frame
  User -> application.get: "1. Enter product detail to update"
  application.post -> application.post.get: "2. Check empty or \n invalid input"
  application.get -> User: "3. Show validation message" {class: return arrow}      
}

application.get -> apiGateway.get: "4. Request update product"
apiGateway.get -> ProductController.get: "5. Forward request"
ProductController -> ProductRepositories.get: "6. Forward request to repository"
ProductRepositories -> ProductDAO.get: "7. Forward request to DAO"

ProductDAO.get -> Supabase.get: "8. Validate token"
Supabase.get -> DB.get: "9. Update new product"
DB.get -> Supabase.get: "10. Return result"
Supabase.get -> ProductDAO.get: "11. Return result"
ProductDAO.get -> ProductRepositories.get: "12. Return result" {class: return arrow}
ProductRepositories.get-> ProductController.get: "13. Forward result" {class: return arrow}

alt: "alt" {
  class: frame
  Update Product Successfully: "[Update Product Successfully]" {
    ProductController.get -> apiGateway.get: "13.1. Return product frontend" {class: return arrow}
    apiGateway.get -> application.get: "13.1.1. Return product" {class: return arrow}
    application.get -> User: "13.1.2. Display Status Successfully" {class: return arrow}
  }
  Product Not Found: "[Product Not Found]" {
    ProductController.get -> apiGateway.get: "13.2. Send error to frontend" {class: return arrow}
    apiGateway.get -> application.get: "13.2.1. Return error" {class: return arrow}
    application.get -> User: "13.2.2. Display error message" {class: return arrow}
  }
}