@startuml 
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class AuthController {
    - _repo: IAuthRepository
    + Logout(): Task<IActionResult> 
}

interface IAuthRepository<<interface>> { 
    + Logout(): Task<IActionResult>
}

class AuthRepository {
    - _dao: AuthDAO
    + Logout(): Task    
}

class AuthDAO {
    - _client: Client
    + Logout(): Task
}

APIGateway -- AuthController

AuthController -- IAuthRepository

IAuthRepository <|-- AuthRepository

AuthRepository -- AuthDAO


@enduml