classes: {
  return_arrow: {
    style: {
      stroke-dash: 3
    }
  }
  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }
}
shape: sequence_diagram
User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}
# Setting
application: "Web Application"
apiGateway: "API Gateway"
TableController: "TableController"
TableRepository: "TableRepository"
TableDAO: "TableDAO"
Supabase: "Supabase"
DB: "Database" {
  shape: cylinder
}

# User Authentication Loop
loop :"loop [Empty or invalid input]"{ 
  class: frame
  User -> application.bar: "1. Enter table information"
  application.bar -> application.get: "2. Check empty and valid input"     
  application.bar -> User: "2.1. Show validation message" {class: return_arrow}           
}   

# Flow
application.bar -> apiGateway.bar: "3. Create Table Request"
apiGateway -> TableController.bar: "4. Forward request"
TableController -> TableRepository.bar: "5. Forward create request"
TableRepository -> TableDAO.bar: "6. Forward request"
TableDAO -> Supabase.post: "7. Check token"
Supabase.post -> DB.post: "8. Check user in database"
DB.post -> TableDAO.bar: "9. Return result" {class:return_arrow}
TableDAO -> DB.bar: "10. Validate and create table"
DB.bar -> TableDAO.bar: "11. Return result" {class:return_arrow}
TableDAO.bar -> TableRepository.bar: "12. Return response" {class:return_arrow}
TableRepository.bar -> TableController.bar: "13. Return response" {class:return_arrow}

# Conditions
alt {
class: frame
"Table created successfully": {
  TableController.bar -> apiGateway.bar: "14.1. Successfully created" {class:return_arrow}
  apiGateway.bar -> application.bar: "14.1.1. Forward response" {class:return_arrow}
  application -> User: "14.1.1.1. Show confirmation message" {class:return_arrow}
}
"Unauthorized access": {
  TableController.bar -> apiGateway.bar: "14.2. Unauthorized request" {class:return_arrow}
  apiGateway.bar -> application.bar: "14.2.1. Forward error" {class:return_arrow}
  application.bar -> User: "14.2.1.1. Display access denied message" {class:return_arrow}
}
"Shop not found": {
  TableController.bar -> apiGateway.bar: "14.3. Shop ID does not exist" {class:return_arrow}
  apiGateway.bar -> application.bar: "14.3.1. Forward error" {class:return_arrow}
  application.bar -> User: "14.3.1.1. Display shop not found message" {class:return_arrow}
}
"Table already exists": {
  TableController.bar -> apiGateway.bar: "14.4. Table number already exists" {class:return_arrow}
  apiGateway.bar -> application.bar: "14.4.1. Forward error" {class:return_arrow}
  application.bar -> User: "14.4.1.1. Display duplicate table message" {class:return_arrow}
}
"Insert failed": {
  TableController.bar -> apiGateway.bar: "14.5. Insert failed" {class:return_arrow}
  apiGateway.bar -> application.bar: "14.5.1. Forward error" {class:return_arrow}
  application.bar -> User: "14.5.1.1. Display insert failed message" {class:return_arrow}
}
}
