@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class ShopController {
    - _shopRepository: IShopRepository
    + CreateShop(CreateShopRequestDTO createShop): Task<IActionResult>
}

interface IShopRepository {
    + CreateShop(CreateShopRequestDTO createShop): Task<GetShopResponseDTO>
}

class ShopRepository {
    - _shopDao: ShopDAO
    + CreateShop(CreateShopRequestDTO createShop): Task<GetShopResponseDTO>
}

class ShopDAO {
    - _client: Client
    - _mapper: IMapper
    + CreateShop(CreateShopRequestDTO createShop): Task<GetShopResponseDTO>
    + GetShopById(Guid shopId): Task<Shop>
    + IsShopNameExists(string name): Task<bool>
}

class CreateShopRequestDTO {
    + Name: string
    + Address: string
    + Description: string
    + OwnerId: Guid
}

class GetShopResponseDTO {
    + Id: Guid
    + Name: string
    + Address: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

class Shop {
    + Id: Guid
    + Name: string
    + Address: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
    + OwnerId: Guid
}

class MappingProfile {
    + MappingProfile()
}

class ErrorHandler {
    + ProcessErrorMessage(string exceptionMessage): string
}

ShopController -- IShopRepository
IShopRepository <|-- ShopRepository
ShopRepository -- ShopDAO
ShopDAO -- Shop
ShopDAO -- GetShopResponseDTO
ShopDAO -- CreateShopRequestDTO
ShopDAO -- ErrorHandler
ShopDAO -- MappingProfile

MappingProfile -- Shop : Maps
MappingProfile -- GetShopResponseDTO : Maps

@enduml
