@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
} 

class ShopController {
    - _shopRepository: IShopRepository
    + DeleteShop(Guid id) : Task<IActionResult> 
}

interface IShopRepository<<interface>> {
    + DeleteShop(Guid id) : Task<DeleteShopRequestDTO> 
}

class ShopRepository {
    - _shopDao: ShopDAO
    + DeleteShop(Guid id) : Task<DeleteShopRequestDTO>
}

class ShopDAO {
    - _client: Client
    - _mapper: IMapper
    + DeleteShop(Guid id) : Task<DeleteShopRequestDTO>
    + GetShopById(Guid id) : Task<GetShopResponseDTO?>
}

class Shop {
    + Id: Guid
    + Name: string
    + Address: string
    + Status: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

APIGateway -- ShopController
ShopController -- IShopRepository
IShopRepository <|-- ShopRepository
ShopRepository -- ShopDAO
ShopDAO -- Shop
@enduml
