@startuml
hide circle
skinparam classAttributeIconSize 0

class APIGateway {
}

class ShopController {
    - _repo: IShopRepository
    + GetAllShops([FromQuery] GetShopRequestDTO request): Task<IActionResult>
}

' Repository Interface
interface IShopRepository<<interface>> {
    + GetAllShops(GetShopRequestDTO request): Task<(List<GetShopResponseDTO>, ShopPaginationDTO)>
}

' Repository Implementation
class ShopRepository {
    - _dao: ShopDAO
    + GetAllShops(GetShopRequestDTO request): Task<(List<GetShopResponseDTO>, ShopPaginationDTO)>
}

' Data Access Object
class ShopDAO {
    - _client: Client
    - _mapper: IMapper
    + GetAllShops(GetShopRequestDTO request): Task<(List<GetShopResponseDTO>, ShopPaginationDTO)>
}

' Domain Model
class Shop {
    + Id: Guid
    + Name: string
    + Address: string
    + OwnerId: Guid
    + PhoneNumber: string
    + Email: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

APIGateway -- ShopController
ShopController -- IShopRepository

IShopRepository <|-- ShopRepository
ShopRepository -- ShopDAO
ShopDAO -- Shop
@enduml
