@startuml
hide circle
skinparam classAttributeIconSize 0

class ShopController {
    - _shopRepository: IShopRepository
    + GetShopById(Guid id) : Task<IActionResult> 
}

interface IShopRepository {
    + GetShopById(Guid id) : Task<GetShopResponseDTO?> 
}

class ShopRepository {
    - _shopDao: ShopDAO
    + GetShopById(Guid id): Task<GetShopResponseDTO?>
}

class ShopDAO {
    - _client: Client
    - _mapper: IMapper
    + GetShopById(Guid id): Task<GetShopResponseDTO?> 
}

class GetShopResponseDTO {
    + Id: Guid
    + Name: string
    + Address: string
    + OwnerId: Guid
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

class Shop {
    + Id: Guid
    + Name: string
    + Address: string
    + OwnerId: Guid
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

class MappingProfile {
  + MappingProfile()
}

class ErrorHandler {
    + IsJson(string input): bool
    + ProcessErrorMessage(string exceptionMessage): string
}

ShopController -- IShopRepository
IShopRepository <|-- ShopRepository
ShopRepository -- ShopDAO
ShopDAO -- Shop
ShopDAO -- GetShopResponseDTO
ShopDAO -- MappingProfile
ShopDAO -- ErrorHandler

MappingProfile -- Shop : Maps
MappingProfile -- GetShopResponseDTO : Maps

@enduml
