@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class ShopController {
    - _shopRepository: IShopRepository
    + UpdateShop(Guid id, UpdateShopRequestDTO updateShop): Task<IActionResult>
}

interface IShopRepository<<interface>> {
    + UpdateShop(Guid id, UpdateShopRequestDTO updateShop): Task<GetShopResponseDTO>
}

class ShopRepository {
    - _shopDao: ShopDAO
    + UpdateShop(Guid id, UpdateShopRequestDTO updateShop): Task<GetShopResponseDTO>
}

class ShopDAO {
    - _client: Client
    - _mapper: IMapper
    + UpdateShop(Guid id, UpdateShopRequestDTO updateShop): Task<GetShopResponseDTO>
    + GetShopById(Guid id): Task<Shop>
    + IsShopNameExists(string name): Task<bool>
}

class Shop {
    + Id: Guid
    + Name: string
    + Address: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
    + OwnerId: Guid
}

APIGateway -- ShopController
ShopController -- IShopRepository
IShopRepository <|-- ShopRepository
ShopRepository -- ShopDAO
ShopDAO -- Shop
@enduml
