label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: "Web application"
apiGateway: "ApiGateway"
AuthController: "AuthController"
AuthRepository: "AuthRepositories"
AuthDAO: "AuthDAO"
Supabase: "Supabase"
DB: "DB" {
  shape: cylinder
}

# Forgot password sequence
loop  { 
  class: frame
  User -> application.post: "1. Enter and submit email"
  application.post -> application.post.get: "2. Check empty and valid input"
  application.post -> User: "3. Show validation message" {class: return arrow}       
}  

application.post -> apiGateway.post: "4. Forward forgot password request"
apiGateway.post -> AuthController.post: "5. Handle forgot password request"
AuthController.post -> AuthRepository.post: "6. Forward to repository"
AuthRepository.post -> AuthDAO.post: "7. Forward to DAO"
AuthDAO.post -> Supabase.post: "8. Validate email"
Supabase.post -> DB.post: "9. Check email in database"
DB.post -> Supabase.post: "10. Return result"
Supabase.post -> AuthDAO.post: "11. Forward reset token"
AuthDAO.post -> AuthRepository.post: "12. Forward reset token"
AuthRepository.post -> AuthController.post: "13. Return reset token"


alt: "alt" {
  class: frame
  Email exists: "[Email exists]" {
    AuthController.post -> apiGateway.post: "17b. Send reset token to frontend"
    apiGateway.post -> application.post: "18b. Return reset token"
    application.post -> User: "19b. Display reset token and instructions"
  }
  Email not found: "[Email not found]" {
    AuthController.post -> apiGateway.post: "13a. Send error to frontend"
    apiGateway.post -> application.post: "14a. Return error"
    application.post -> User: "15a. Display error message"
  }
}