@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho



class APIGateway {
}
class TableController {
    - _tableRepository: ITableRepository
    +  GetTableById(Guid id) : Task<IActionResult> 
}

interface ITableRepository<<interface>>  {
    + GetTableById(Guid id) : Task<GetTableResponseDTO?> 
}

class TableRepository {
    - _tableDao: TableDAO
    + GetTableById(Guid id): Task<GetTableResponseDTO?>
}
class TableDAO {
    - _client: Client
    - _mapper: IMapper
    + GetTableById(Guid id):Task<GetTableResponseDTO?> 
    + IsTypeExists(Guid typeId): Task<bool> 
}

class Table {
    + Id: Guid
    + TableNumber: string
    + Capacity: int
    + Status: string
    + Description: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
    + ShopId: Guid
    + TypeId: Guid
}
class TableType {
    + Id: Guid
    + Name: string
    + Description: string
    + PriceByHour: decimal
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

APIGateway -- TableController
TableController -- ITableRepository
ITableRepository <|-- TableRepository
TableRepository -- TableDAO
TableDAO -- Table
TableDAO -- TableType


@enduml