label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: Web application
apiGateway: ApiGateway
Router: Router
AuthController: AuthController
AuthRepository: AuthRepository
AuthDAO: AuthDAO
Supabase: "Supabase"

DB: "DB" {
  shape: cylinder
}

# User registration sequence
loop  { 
  class: frame
  User -> application.post: "1. Enter credentials and submit register form"
  application.post -> application.post.get: "2. Check empty or \n invalid input"
  application.post -> User: "3. Show validation message" {class: return arrow}      
    
}  
 
application -> apiGateway.post: "4. Forward registration request"
apiGateway.post -> Router.post: "5. Send create account request"
Router.post -> AuthController.post: "6. Forward to controller"
AuthController -> AuthRepository.post: "7. Forward to repository"
AuthRepository -> AuthDAO.post: "8. Forward to DAO"
AuthDAO.post -> Supabase.post: "9. Validate user and password"
Supabase.post-> DB.insert: "10. Insert new account record"
DB.insert -> Supabase.post: "11. Return result"
Supabase.post -> AuthDAO.post: "12. Return result" {class: return arrow}
AuthDAO.post -> AuthRepository.post: "13. Forward result" {class: return arrow}
AuthRepository.post -> AuthController.post: "14. Return result" {class: return arrow}


alt: "alt" {
  class: frame
  Registration successful: "[Registration successful]" {
    AuthController.post -> Router.post: "14.1. Send success status to frontend" {class: return arrow}
    Router.post -> apiGateway.post: "14.1.1. Return success status" {class: return arrow}    
    apiGateway.post -> application.post: "14.1.2. Return success status" {class: return arrow}
    application.post -> User: "14.1.3. Display registration success message" {class: return arrow}
  }
  Registration failed: "[Registration failed]" { 
    AuthController.post -> apiGateway.post: "14.2. Send error status to frontend" {class: return arrow}
    Router.post -> apiGateway.post: "14.2.1. Return error status" {class: return arrow}    
    apiGateway.post -> application.post: "14.2.2. Return error status" {class: return arrow}
    application.post -> User: "14.2.3. Display registration error message" {class: return arrow}
  }
}
