label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: Web application
apiGateway: ApiGateway
SubscriptionController: SubscriptionController
SubscriptionRepository: SubscriptionRepository
SubscriptionDAO: SubscriptionDAO
Supabase: "Supabase"

DB: "DB" {
  shape: cylinder
}

# User registration sequence
loop  { 
  class: frame
  User -> application.post: "1. Enter Update Subscription form"
  application.post -> application.post.get: "2. Check empty and valid input"    
  application.post -> User: "3. Show validation message" {class: return arrow}        
}  
 
application -> apiGateway.post: "4. Forward Update Subscription request"
apiGateway -> SubscriptionController.post: "5. Forward Update Subscription request"
SubscriptionController -> SubscriptionRepository.post: "6. Forward to repository"
SubscriptionRepository -> SubscriptionDAO.post: "7. Forward to DAO"
SubscriptionDAO.post -> Supabase.post: "8. Validate token"
Supabase.post-> DB.insert: "9. Update Subscription By Id"
DB.insert -> Supabase.post: "19. Return result" {class: return arrow}
Supabase.post -> SubscriptionDAO.post: "11. Return result" {class: return arrow}
SubscriptionDAO.post -> SubscriptionRepository.post: "12. Forward result" {class: return arrow}
SubscriptionRepository.post -> SubscriptionController.post: "13. Return result" {class: return arrow}


alt: "alt" {
  class: frame
  Registration successful: "[Update successful]" {
    SubscriptionController.post -> apiGateway.post: "13.1. Send success status to frontend" {class: return arrow}
    apiGateway.post -> application.post: "13.1.1. Return success status" {class: return arrow}
    application.post -> User: "13.1.2. Display update success message" {class: return arrow}
  }
  Registration failed: "[Subscription Id not found]" { 
    SubscriptionController.post -> apiGateway.post: "13.2. Send error status to frontend" {class: return arrow}
    apiGateway.post -> application.post: "13.2.1. Return error status" {class: return arrow}
    application.post -> User: "13.2.2. Display error message" {class: return arrow}
  }
}
