@startuml 
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class AuthController {
    - _repo: IAuthRepository
    +ChangePassword([FromBody] ChangePasswordRequestDTO requestDTO): Task<IActionResult> 
}


interface IAuthRepository<<interface>> { 
    + ChangePassword(ChangePasswordRequestDTO request, string token): Task
}

class AuthRepository {
    - _dao: AuthDAO
    + ChangePassword(ChangePasswordRequestDTO request, string token): Task    
}

class AuthDAO {
    - _client: Client
    + ChangePassword(ChangePasswordRequestDTO request, string token): Task
}


class Profile {
    + Id: Guid
    + FullName: string
    + ProfilePicture: string
    + Bio: string
    + DateOfBirth: DateTime
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
    + Role: string
    + AccountId: Guid
}

APIGateway -- AuthController
AuthController -- IAuthRepository

IAuthRepository <|-- AuthRepository

AuthRepository -- AuthDAO


AuthDAO -- Profile
@enduml