@startuml 
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class UserController{
    - _repo: IUserRepository
    + CreateProfile([FromBody] CreateProfileRequestDTO request): Task<IActionResult>
}

interface IUserRepository<<interface>> {
    + CreateUser(CreateProfileRequestDTO request, string token): Task<GetUserResponeDTO>
}

class UserRepository {
    - _dao: UserDAO
    + CreateUser(CreateProfileRequestDTO request, string token): Task<GetUserResponeDTO>
}

class UserDAO {
    - _client: Client
    + CreateUser(CreateProfileRequestDTO request, string token): Task<GetUserResponeDTO>
}

class Profile {
    + Id: Guid
    + FullName: string
    + ProfilePicture: string
    + Bio: string
    + DateOfBirth: DateTime
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
    + Role: string
    + AccountId: Guid
}

APIGateway -- UserController
UserController -- IUserRepository 
IUserRepository <|-- UserRepository
UserRepository -- UserDAO
UserDAO -- Profile

@enduml