label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return_arrow: {
    style: {
      stroke-dash: 3
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label_right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: "Application"
apiGateway: "API Gateway"
TableController: "TableController"
TableRepository: "TableRepository"
TableDAO: "TableDAO"
DB: "DB" {
  shape: cylinder
}

# Get all tables sequence
User -> application.bar: "1. View all tables"
User -> application.bar: "2. Select filters"
application -> apiGateway.bar: "3. Forward request"
apiGateway -> TableController.bar: "4. Forward to TableController"
TableController -> TableRepository.bar: "5. Call GetAllTables()"
TableRepository -> TableDAO.bar: "6. Fetch tables from DB"

# Query database with filters
TableDAO -> DB.bar: "7. Query tables with filters"
DB.bar -> TableDAO.bar: "8. Return table list" {class:return_arrow}
alt: "alt" {
  class: frame
  Incorrect credentials: "[No tables found]" {
  # Conditional branch for incorrect credentials
  TableDAO.bar -> TableRepository.bar: "9a. Return empty response"{class:return_arrow}
  TableRepository.bar -> TableController.bar: "10a. Return empty response"{class:return_arrow}
  TableController.bar -> apiGateway.bar: "11a. Send empty response"{class:return_arrow}
  apiGateway.bar -> application.bar: "12a. Forward empty response"{class:return_arrow}
  application.bar -> User: "13a. Display empty table list"{class:return_arrow}
  }
  Correct credentials: "[Tables found]" {
    # Successful login branch
    TableDAO.bar -> TableRepository.bar: "9b. Return tables with filter"{class:return_arrow}
    TableRepository.bar -> TableController.bar: "10b. Return tables data"{class:return_arrow}
    TableController.bar -> apiGateway.bar: "11b. Send response"{class:return_arrow}
    apiGateway.bar -> application.bar: "12b. Forward response"{class:return_arrow}
    application.bar -> User: "13b. Display table list"{class:return_arrow}
  }
}

