@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class ProductController {
    - _repo: IProductRepository
    + CreateProduct([FromBody] CreateProductRequestDTO request): Task<IActionResult>
}

interface IProductRepository<<interface>> {
    + CreateProduct(CreateProductRequestDTO request, string token): Task
}

class ProductRepository {
    - _dao: ProductDAO
    + CreateProduct(CreateProductRequestDTO request, string token): Task
}

class ProductDAO {
    - _client: Client
    + CreateProduct(CreateProductRequestDTO request, string token): Task
}

class MenuItem {
    + Id: Guid
    + ShopId: Guid
    + Name: string
    + Price: decimal
    + Description: string
    + Category: string
    + IsAvailable: bool
    + Ingredient: string
    + NutritionalIfo: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

APIGateway -- ProductController
ProductController -- IProductRepository 
IProductRepository <|-- ProductRepository
ProductRepository -- ProductDAO
ProductDAO -- MenuItem

@enduml
