@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class ProductController {
    - _repo: IProductRepository
    + DeleteProduct(Guid id): Task<IActionResult>
}

interface IProductRepository<<interface>> {
    + DeleteProduct(Guid id): Task
}

class ProductRepository {
    - _dao: ProductDAO
    + DeleteProduct(Guid id): Task
}

class ProductDAO {
    - _client: Client
    + DeleteProduct(Guid id): Task
}

class MenuItem {
    + Id: Guid
    + ShopId: Guid
    + Name: string
    + Price: decimal
    + Description: string
    + Category: string
    + IsAvailable: bool
    + Ingredient: string
    + NutritionalIfo: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}



APIGateway -- ProductController
ProductController -- IProductRepository
IProductRepository <|-- ProductRepository
ProductRepository -- ProductDAO
ProductDAO -- MenuItem
@enduml
 