@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}
' Controllers
class ProductController {
    - _repo: IProductRepository
    + GetAllProducts([FromQuery] GetProductRequestDTO request): Task<IActionResult>
}

' Repository Interface
interface IProductRepository {
    + GetAllProducts(GetProductRequestDTO request): Task<(List<GetProductResponseDTO>, ProductPaginationDTO)>
}

' Repository Implementation
class ProductRepository {
    - _dao: ProductDAO
    + GetAllProducts(GetProductRequestDTO request): Task<(List<GetProductResponseDTO>, ProductPaginationDTO)>
}

' Data Access Object
class ProductDAO {
    - _client: Client
    - _mapper: IMapper
    + GetAllProducts(GetProductRequestDTO request): Task<(List<GetProductResponseDTO>, ProductPaginationDTO)>
}

' Domain Model
class MenuItem {
    + Id: Guid
    + ShopId: Guid
    + Name: string
    + Price: decimal
    + Description: string
    + Category: string
    + IsAvailable: bool
    + Ingredient: string
    + NutritionalInfo: string
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}


' Relationships
APIGateway -- ProductController
ProductController -- IProductRepository

IProductRepository <|-- ProductRepository
ProductRepository -- ProductDAO
ProductDAO -- MenuItem

@enduml
