@startuml 
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class AuthController {
    - _repo: IAuthRepository
    + RecoverPassword([FromBody] RecoverPasswordRequestDTO requestDTO): Task<IActionResult> 
}

interface IAuthRepository<<interface>> {
    + ResetPassword(RecoverPasswordRequestDTO request): Task
}

class AuthRepository {
    - _dao: AuthDAO
    + ResetPassword(RecoverPasswordRequestDTO request): Task
}

class AuthDAO {
    - _client: Client
    + ResetPassword(RecoverPasswordRequestDTO request): Task
}

class Profile {
    + Id: Guid
    + FullName: string
    + ProfilePicture: string
    + Bio: string
    + DateOfBirth: DateTime
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
    + Role: string
    + AccountId: Guid
}


APIGateway -- AuthController

AuthController -- IAuthRepository

IAuthRepository <|-- AuthRepository

AuthRepository -- AuthDAO

AuthDAO -- Profile
@enduml