@startuml createSubscription
hide circle
skinparam classAttributeIconSize 0
skinparam linetype ortho

class APIGateway {
}

class SubscriptionController{
    - _repo: ISubscriptionRepositories
    + Create(CreateSubscriptionRequestDTO request): Task<IActionResult>
}

interface ISubscriptionRepositories<<interface>> {
    + CreateSubscription(CreateSubscriptionRequestDTO request, string token): Task
}

class SubscriptionRepositories {
    - _dao: UserDAO
    + CreateSubscription(CreateSubscriptionRequestDTO request, string token): Task
}

class SubscriptionDAO {
    - _client: Client
    + Create(CreateSubscriptionRequestDTO request, string token): Task
}

class Subscriptions {
    + Id: Guid
    + Name: string
    + Price: decimal
    + Description: string
    + NumberOfMonths: DateTime
    + CreatedAt: DateTime
    + UpdatedAt: DateTime
}

APIGateway -- SubscriptionController
SubscriptionController -- ISubscriptionRepositories
ISubscriptionRepositories <|-- SubscriptionRepositories
SubscriptionRepositories "1"--"1..*" SubscriptionDAO
SubscriptionDAO "1"--"0..*" Subscriptions

@enduml