label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: "Web application"
apiGateway: "ApiGateway"
AuthController: "AuthController"
AuthRepository: "AuthRepository"
AuthDAO: "AuthDAO"
Supabase: "Supabase"

DB: "DB" {
  shape: cylinder
}

# Recover password sequence
loop  { 
  class: frame
  User -> application.post: "1. Enter OTP and New Password"
  application.post -> application.post.get: "2. Check empty or \n invalid input"
  application.post -> User: "3. Show validation message" {class: return arrow}      
}  

application -> apiGateway.post: "4. Forward reset password request"
apiGateway -> AuthController.post: "5. Handle reset password request"
AuthController -> AuthRepository.post: "6. Forward to repository"
AuthRepository -> AuthDAO.post: "7. Forward to DAO"
AuthDAO.post -> Supabase.post: "8. Validate OTP and new password"
Supabase.post -> DB.post: "9. Update Password"
DB.post -> Supabase.post: "10. Return success status" {class: return arrow}
Supabase.post -> AuthDAO.post: "11. Return success status" {class: return arrow}
AuthDAO.post -> AuthRepository.post: "12. Forward success status" {class: return arrow}
AuthRepository.post -> AuthController.post: "13. Return success status" {class: return arrow}


alt: "alt" {
  class: frame
  Reset successful: "[Reset successful]" {
    AuthController -> apiGateway.post: "13.1. Send success status to frontend" {class: return arrow}
    apiGateway -> application.post: "13.1.1. Return success status" {class: return arrow}
    application -> User: "13.1.1. Display password reset success message" {class: return arrow}
  }
  Reset failed: "[Reset failed]" {
    AuthController -> apiGateway.post: "13.2. Send error status to frontend" {class: return arrow}
    apiGateway.post -> application.post: "13.2.1. Return error status" {class: return arrow}
    application.post -> User: "13.2.2. Display error message"
  }
}